# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummerSchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('content', models.FileField(upload_to='image')),
            ],
        ),
    ]
