# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummerSchoolApp', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='content',
            field=models.FileField(upload_to='media/image'),
        ),
    ]
