# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummerSchoolApp', '0003_auto_20170222_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='date',
        ),
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AddField(
            model_name='image',
            name='year',
            field=models.IntegerField(default=2012),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='year',
            field=models.IntegerField(default=2012),
            preserve_default=False,
        ),
    ]
