# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SummerSchoolApp', '0004_auto_20170223_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='media/review_image')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SummerSchoolApp.Review')),
            ],
        ),
    ]
