# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummerSchoolApp', '0005_reviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.IntegerField(default=1)),
                ('course_no', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=100)),
                ('credit', models.IntegerField(default=3)),
                ('professor', models.CharField(max_length=50)),
                ('syllabus', models.FileField(upload_to='media/syllabus')),
            ],
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('academic_schedule', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
