# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummerSchoolApp', '0006_course_importantdate_questionandanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_edu_3',
            field=models.BooleanField(default=False),
        ),
    ]
