# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SummerSchoolApp', '0007_course_is_edu_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='Photo', max_length=100),
        ),
    ]
