# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SummerSchoolApp', '0009_auto_20170303_0438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='number',
        ),
        migrations.RemoveField(
            model_name='importantdate',
            name='number',
        ),
        migrations.RemoveField(
            model_name='review',
            name='number',
        ),
    ]
